name: grafana
title: Grafana
icon: grafana

services:
- name: grafana
  title: Grafana
  service: grafana
  required: true
  main: true
  volumes:
  - name: data
    size: 10
  workloads:
  - name: main
    containers:
    - name: grafana
      resources:
        request:
          cpu: 200
          memory: 512
        limit:
          cpu: 1000
          memory: 1024
